const { default: mongoose } = require("mongoose");
const Event = require("../../models/Event");
const EventSession = require("../../models/EventSession");
const QueryBuilder = require("../../services/queryBuilder");
const catchAsync = require("../../utils/catchAsync");
const { successRes } = require("../../utils/responseFormatter");
const AppError = require("../../utils/AppError");
const GatekeeperScan = require("../../models/GatekeeperScan");
const ENVIRONMENT = require("../../config/env.js");
const { isValidId } = require("../../helper/productHelper.js");
const TicketBooking = require("../../models/TicketBooking.js");

const generateTicketFromAdminSide = catchAsync(async (req, res, next) => {
    let {
        sessionId,
        eventId,
        quantity,
        isVipTicket = false,
        isValidForAllDays = false
    } = req.body;

    // 🔹 Validate IDs
    if (!isValidId(sessionId)) return next(new AppError("Invalid session id", 400));
    if (!isValidId(eventId)) return next(new AppError("Invalid event id", 400));

    // 🔹 Validate quantity
    if (!quantity) return next(new AppError("Quantity is required", 400));
    quantity = parseInt(quantity, 10);
    if (isNaN(quantity) || quantity <= 0) {
        return next(new AppError("Quantity must be a positive integer", 400));
    }

    // 🔹 Limit per booking (Admin override allowed via env)
    const limitPerBooking = parseInt(process.env.MAX_TICKETS_PER_BOOKING || 50, 10);
    if (quantity > limitPerBooking) {
        return next(new AppError(`You can book a maximum of ${limitPerBooking} tickets at a time`, 400));
    }

    // 🔹 Validate session
    const sessionData = await EventSession.findOne({
        _id: sessionId,
        event: eventId,
        isDeleted: false
    });
    if (!sessionData) return next(new AppError("Event session not found", 404));

    // 🔹 Validate event
    const eventData = await Event.findOne({ _id: eventId, isDeleted: false });
    if (!eventData) return next(new AppError("Event not found", 404));

    // 🔹 Expiry check
    const now = new Date();
    if (sessionData.date < now) {
        return next(new AppError("This event session has already expired", 400));
    }

    // 🔹 Price calculation
    const pricePerTicket = sessionData.pricePerTicket || eventData.price || 0;
    const totalAmount = pricePerTicket * quantity;

    // 🔹 Final flag for validity
    const finalIsValidForAllDays = isVipTicket ? true : !!isValidForAllDays;
    console.log("finalIsValidForAllDays", finalIsValidForAllDays)
    // 🔹 Attendee details (condition based)
    const attendeeName = isVipTicket ? "VIP Ticket" : "Admin Normal Ticket";
    const attendeeDetails = Array.from({ length: quantity }, (_, i) => ({
        name: `${attendeeName} ${i + 1}`,
        phone: ""
    }));

    // 🔹 Capacity check (only for normal non-allDay tickets)
    if (!isVipTicket && !finalIsValidForAllDays) {
        if (sessionData.remainingCapacity < quantity) {
            return next(new AppError("Not enough tickets available", 400));
        }
    }

    // 🔹 Create booking (without payment)
    const booking = await TicketBooking.create({
        user: req.user._id, // Admin ID
        eventSession: sessionId,
        event: eventId,
        quantity,
        attendeeDetails,
        pricePerTicket,
        totalAmount,
        currency: "INR",
        paymentMethod: "razorpay", // keeping enum value same
        paymentStatus: "paid",     // mark as paid since admin generated
        ticketStatus: "pending",   // can later be confirmed
        tickets: [],
        notes: "Admin generated booking",
        generatedBy: "admin",
        isVipTicket,
        validForAllDays: finalIsValidForAllDays
    });

    // 🔹 Update session capacity only if applicable
    if (!isVipTicket && !finalIsValidForAllDays) {
        sessionData.remainingCapacity -= quantity;
        await sessionData.save();
    }

    return successRes(
        res,
        201,
        true,
        "Tickets generated by admin successfully",
        { bookingId: booking._id }
    );
});

const getTicketsBySessionId = catchAsync(async (req, res, next) => {
    const { sessionId, page = 1, limit = 10 } = req.query;

    if (!isValidId(sessionId)) return next(new AppError('Invalid session id', 400));

    // Count total tickets
    const countBuilder = new QueryBuilder(TicketBooking);
    const totalTickets = await countBuilder
        .filter({ eventSession: new mongoose.Types.ObjectId(sessionId) })
        .count();

    // Fetch paginated tickets
    let qb = new QueryBuilder(TicketBooking);
    const tickets = await qb
        .aggregate([
            {
                $match: {
                    eventSession: new mongoose.Types.ObjectId(sessionId),
                },
            },
            {
                $lookup: {
                    from: "users",
                    localField: "user",
                    foreignField: "_id",
                    as: "userDetails",
                },
            },
            { $unwind: "$userDetails" },
            { $skip: (parseInt(page, 10) - 1) * parseInt(limit, 10) },
            { $limit: parseInt(limit, 10) }
        ])
        .exec();

    return successRes(res, 200, true, "Tickets fetched successfully", {
        total: totalTickets,
        page: parseInt(page, 10),
        limit: parseInt(limit, 10),
        data: tickets
    });
});

const getTicketById = catchAsync(async (req, res, next) => {
    const ticketId = req.query.ticketId;

    if (!isValidId(ticketId)) {
        return next(new AppError('Invalid ticket id', 400));
    }

    const qb = new QueryBuilder(TicketBooking);
    const ticket = await qb
        .filter({ _id: new mongoose.Types.ObjectId(ticketId) })
        .populate("user", "-password") // Adjust fields as needed
        .exec();

    if (!ticket) {
        return next(new AppError('Ticket not found', 404));
    }

    return successRes(res, 200, true, "Ticket fetched successfully", ticket);
});


module.exports = {
    getTicketsBySessionId,
    getTicketById,
    generateTicketFromAdminSide
}